### ISSUE TITLE
Report version 6.61

### ISSUE THREAD

**Issue by KnightRlex** [joel16/CyanogenPSP#11]
Hi friend, i dowload the 6.61 and i found 4 problems:
1. calculator doesnt work
2. message doesnt work
3. when i leave a game, return me to the menu of psp
4. i cant view images

PD: i have a psp 1000 (fat) and the CF pro 6.61 permanent

**Comment by joel16** [comment]
Calculator and messages were never finished. Also I've discontinued this project a long time ago, I'm no longer supporting it, sorry.
