### ISSUE TITLE
Ability to "toggle usbhost" from irshell?

### ISSUE THREAD

**Issue by raku-cat** [joel16/CyanogenPSP#8]
I noticed you still seem to be somewhat working on this, do you think it would be possible to add the toggle usbhost function from irshell(as referenced here http://wololo.net/talk/viewtopic.php?f=28&t=4901 under linux instructions), I've been trying to get remotejoy to work, and the remotejoylite toggle  under debug doesn't seem to do the trick.

**Comment by joel16** [comment]
That's weird cause it definitely works for me. Make sure you don't have RJL enabled in your plugins, it might interfere.

**Comment by raku-cat** [comment]
Think you could give an exact step by step process just to make sure we aren't losing anything in translation? I'm on Linux by the way, which in sure is part of the problem.

**Comment by joel16** [comment]
Are you using google translate?

Well anyways, here are the steps:

1. Make sure Remote Joy Lite is not enabled as a plugin in your custom firmware (CFW) . USB host should be disabled too.

2. Open CyanogenPSP, go to developer options and toggle Remote Joy Lite. It should work now.

**Comment by raku-cat** [comment]
Not using google translate, just means making sure I'm not doing something you aren't or likewise.
That said, I couldn't get it working, here's a few files that might help:

- Directory listing of my /seplugins - https://ptpb.pw/ed6m
- VSH.TXT - https://ptpb.pw/fxOH
- POPS.TXT - https://ptpb.pw/-wqH
- GAME.TXT - https://ptpb.pw/K9Od
- Output of lsusb - https://ptpb.pw/KuF0
- Output of usbhostfs_pc -vv - https://ptpb.pw/QrgW
- Output of remotejoy -v -d -c - https://ptpb.pw/dsg5

Exact list of steps I took:

1. Started usbhostfs_pc with sudo
2. Launched remotejoy as non-root user
3. Turned on PSP still unplugged
4. Plugged in PSP
5. Started CyanogenPSP
6. Toggled Remote Joy Lite

Also few things worth noting:
My computer is running Arch linux, my PSP is a psp go model "PSP-N1001" , I am running the infinity patch with 6.61 using lme cfw 2.3.

Please let me know if there's anything else you could use.

**Comment by joel16** [comment]
My PSP GO is also running 6.61 Inifity, but it runs on PRO CFW rather than ME.
I don't have a telegram, and I don't go on irc much because I'm currently enrolled as a full time student in University, therefore spending most of my days with university related stuff. I get free around 11 PM (central time)

However I noticed one thing. You have "ef0:/seplugins/remotejoy.prx 1" in game.txt, try changing that to  "ef0:/seplugins/remotejoy.prx 0". 

Anyways honestly, its better using the RJL plugin rather than the one CyanogenPSP hooks into. It used to have usb host toggle, but it never ran efficiently as it would as a plugin.

**Comment by raku-cat** [comment]
I was running pro c at one point and tried it, same result, also tried it with pretty much every plugin disabled(including the one you mentioned).

**Comment by joel16** [comment]
Hm, just use the original RJL plugin I guess. I'll try looking into this later, but I can't say it would be anytime soon, sorry. I'm currently working on porting this to vita for the Gekihen competition.

**Comment by joel16** [comment]
Wait are you trying to get remote joy lite working or usbhost?
Are you trying to display your PSP's screen on your computer?

**Comment by raku-cat** [comment]
PSP screen on comp. Would like to proudly say I got it working, so everything is all good! Thanks for taking the time to respond though and being patient with me! Good luck with uni and the competition :)
